# Generated by Django 3.2.8 on 2022-04-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awsvirtualmachine',
            name='instance_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Instance ID'),
        ),
    ]
